/**
 * @compatibility nodejs_compat
 * @compatibility-date 2026-03-18
 */
export default {
  fetch(request, env, ctx) {
    // This file is automatically generated by next-on-pages
    // The compatibility flag is added here to ensure it's picked up
  },
};
